server:
  port: 9003
logging:
  level:
    org.springframework.web: info
    com.github.binarywang.demo.wx.miniapp: debug
    cn.binarywang.wx.miniapp: debug
wx:
  miniapp:
    configs:
      - appid: wxca07de8fce1e1824
        secret: e4a0c1e622dc912996d494f92d754b08
        token: IKATSCHIGOOSE
        aesKey: HRbAqjsLUJ2RtFAnQIIsGp9AFV29OmQFfjsDEcLKY2k
        msgDataFormat: JSON
